apps/clientes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',
        views.ClientesListView.as_view(), name='clientes-list'),
    url(r'^new/$',
        views.ClientesNewView.as_view(), name='clientes-new'),
    url(r'^(?P<id>[\w\- ]+)/edit/$',
        views.ClientesUpdateView.as_view(), name='clientes-edit'),
    url(r'^(?P<id>[^/]+)/delete/$',
        views.ClientesDeleteView.as_view(), name="clientes-delete"),

    #CRUD BASICO
	url(r'^crud-r/$', views.crud_r, name='crud-r'),
	url(r'^crud-c/$', views.crud_c, name='crud-c'),
	url(r'^crud-u/(?P<cliente_id>[\w\- ]+)/edit/$', views.crud_u, name='crud-u'),
    url(r'^crud-d/(?P<cliente_id>[\w\- ]+)/delete/$', views.crud_d, name='crud-d')

]

sesion3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
	url(r'^', include('apps.home.urls')),
	url(r'^clientes/', include('apps.clientes.urls')),
    path('admin/', admin.site.urls),
]

apps/clientes/models.py
from django.db import models
import uuid

# Create your models here.

class Cliente(models.Model):	

	    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	    first_name = models.CharField( null=False,max_length=255,
	        blank=False, verbose_name='Firts name')
	    last_name = models.CharField(max_length=255,
	       null=False, blank=False, verbose_name='Last name')
	    address = models.CharField(max_length=400,
	       null=False, blank=False, verbose_name='Address')
	    phone = models.CharField(max_length=20,
	        null=False, blank=False, verbose_name='Teléfono')
	    email = models.EmailField(
	        null=False, blank=False, verbose_name='Email')

	    status = models.BooleanField(
	        default=True,  verbose_name='Status')
	    created_at = models.DateTimeField(auto_now_add=True)
	    updated_at = models.DateTimeField(auto_now=True)

	    class Meta:  # noqa
	        verbose_name = 'Cliente'
	        verbose_name_plural = 'Clientes'
	        default_related_name = 'cliente'
	        db_table = 'clientes'
	        ordering = ['-created_at']

	    def __unicode__(self):
	        u"""Customer."""
	        # return u'%s' % self.full_name
	        return str(self.full_name)

	    def __str__(self):
	            return '%s' % (self.full_name)

	    @property
	    def full_name(self):
	        """Nombre completo del cliente.

	        :attribute: full_name
	        :type: String
	        :return: self.get_full_name()
	        """
	        return self.get_full_name()

	    def get_full_name(self):
	        u"""Devuelve el nombre completo del cliente.

	        Devuelve una unión de el nombre y el apellido del cliente.

	        :return: u'%s %s' % (self.first_name, self.last_name)
	        """
	        return u'%s %s' % (self.first_name, self.last_name)
	
		

apps/clientes/forms.py
from django.forms import ModelForm, Textarea
from apps.clientes.models import Cliente

from django import forms


class ClienteForm(ModelForm):

    first_name = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={'class': 'form-control'}) )
    last_name = forms.CharField(label= 'Apellido', widget=forms.TextInput(attrs={'class': 'form-control'}) )
    address = forms.CharField(label= 'Dirección', widget=forms.Textarea( attrs={'class': 'form-control', 'rows':'5','cols':'12' }) )
    phone = forms.CharField(label= 'Teléfono', widget=forms.NumberInput(attrs={'class': 'form-control'}) )
    email = forms.CharField(required=False, label= 'Email', widget=forms.TextInput(attrs={'class': 'form-control'}) )
    status = forms.BooleanField(required=False, initial=True, label= 'Estado', widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}) )

    class Meta:
        model = Cliente
        fields = (
        	'first_name',
        	'last_name',
        	'address',
        	'phone',
        	'email',
            'status'
       		)
        

apps/clientes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.clientes.models import Cliente
from . import forms
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.db.models import Value
from django.db.models.functions import Concat

class ClientesListView(ListView):    

    template_name = 'clientes/index.html'
    model = Cliente
    context_object_name = 'clientes'
    paginate_by =  4

    def get_queryset(self):        
        queryset = super(ClientesListView, self).get_queryset()        

        queryset = Cliente.objects.all()        
        if 'name' in self.request.GET:
            name = self.request.GET['name']
            queryset = queryset.annotate(search_name=Concat('first_name', Value(' '), 'last_name'))
            queryset = queryset.filter(search_name__icontains=name)

        return queryset

    def get_context_data(self, **kwargs):   # noqa
        context = super(ClientesListView, self).get_context_data(**kwargs)

        if 'name' in self.request.GET:
            name = self.request.GET['name']            
            context['name'] = name

        return context


class ClientesNewView(CreateView):    

    template_name = 'clientes/new.html'
    model = Cliente
    form_class = forms.ClienteForm
    success_url = reverse_lazy('super:clientes-list')

    def get_context_data(self, **kwargs):   # noqa
        context = super(ClientesNewView, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):        
        self.object = form.save(commit=False)
        self.object.save()

        return super(ClientesNewView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            "Creación exitosa")
        if 'save-and-add' in self.request.POST:
            return reverse('clientes-list')
        else:
            return reverse('clientes-edit', args=[self.object.id, ])

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            "Por favor corrige los errores de abajo.")
        return self.render_to_response(self.get_context_data(form=form))


class ClientesUpdateView(UpdateView):
    """."""

    template_name = 'clientes/edit.html'
    model = Cliente
    form_class = forms.ClienteForm
    pk_url_kwarg = 'id'
    context_object_name = 'cliente'

    def get_queryset(self):        
        queryset = super(ClientesUpdateView, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):   # noqa
        context = super(ClientesUpdateView, self).get_context_data(**kwargs)       
        return context

    def form_valid(self, form):
        return super(ClientesUpdateView, self).form_valid(form)

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            "Actualización exitosa.")
        if 'save-and-add' in self.request.POST:
            return reverse('clientes-new')
        else:
            return reverse('clientes-edit', args=[self.object.id, ])

    def form_invalid(self, form):
        """."""
        messages.add_message(
            self.request, messages.ERROR,
            "Por favor corrige los errores de abajo.")
        return self.render_to_response(self.get_context_data(form=form))


class ClientesDeleteView(DeleteView):
    """."""

    template_name = 'clientes/delete.html'
    model = Cliente
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        """Judge Delete."""
        context = super(ClientesDeleteView, self).get_context_data(**kwargs)

        cliente = get_object_or_404(Cliente, id = self.object.id)             
        context['cliente'] = cliente
      
        return context

    def get_queryset(self):        
        queryset = super(ClientesDeleteView, self).get_queryset()
        return queryset

    def get_success_url(self):
        """."""
        messages.add_message(
            self.request, messages.SUCCESS,
            "El objeto se ha borrado exitosamente")
        return reverse('clientes-list')


def crud_r(request):
    clientes = Cliente.objects.all()  # se obtienen todos los clientes
    context = {'clientes': clientes}   
    return render(request, 'clientes/crud_r.html', context) 

def crud_c(request):
    context = { }

    form = forms.ClienteForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('crud-r')

    context['form'] = form
    return render(request, 'clientes/crud_c.html', context)

def crud_u(request, cliente_id):

    try:
        cliente = Cliente.objects.get(pk=cliente_id)
    except Exception as e:
        return render(request, 'clientes/404.html')

    form = forms.ClienteForm(request.POST or None, instance=cliente)

    if form.is_valid():
        form.save()
        return redirect('crud-r')

    context = { 'form': form }
    return render(request, 'clientes/crud_u.html', context)

def crud_d(request, cliente_id):
    try:
        cliente = Cliente.objects.get(pk=cliente_id)
    except Exception as e:
        return render(request, 'clientes/404.html')

    if request.POST:
        cliente.delete()
        return redirect('crud-r')

    context = { 'cliente': cliente }
    return render(request, 'clientes/crud_d.html', context )

apps/clientes/templates/clientes/crud_c.html
<html>
	<head>
		<title>Crea cliente</title>
	</head>
	<body>
		<h1>Crear cliente</h1>
		<a href="{% url 'crud-r'%}">Regresar</a>
		<form action="" method="POST">
			{% csrf_token%}

			{{form.as_p}}
			<a href="{% url 'crud-r'%}">Cancelar</a>
			<input type="submit" name="submit" value="Guardar">
		</form>
	</body>
</html>								

apps/clientes/templates/clientes/crud_d.html
<html>
	<head>
		<title>Borrar cliente</title>
	</head>
	<body>
		<h1>Borrar cliente</h1>
		<p>Realmente desea borrar al cliente: {{cliente.full_name}}?</p>
		<form action="" method="post">
			{% csrf_token %}
			
			<input type="submit" name="submit" value="Sí, borar">
			<br>
			<a href="{% url 'crud-r'%}">No, regresar</a>
		</form>
	</body>							
</html>

apps/clientes/templates/clientes/crud_r.html
<html>
	<head>
		<title>Lista clientes</title>
	</head>
	<body>
		<h1>Lista clientes</h1>

		<a href="{% url 'crud-c' %}">Crear cliente</a>
		<br>
		<br>
		<table border="1">
			<thead>
				<th>Nombre</th>
				<th>Apellido</th>
				<th>Opciones</th>
			</thead>
			<tbody>
				{% for cliente in clientes %}
					<tr>
					 	<td>{{cliente.first_name}}</td>
						<td>{{cliente.last_name}}</td>
						<td>
							<a href="{% url 'crud-d' cliente.id %}">Borrar</a>
							<a href="{% url 'crud-u' cliente.id %}">Editar</a>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>																																																																																															

apps/clientes/templates/clientes/crud_u.html
<html>
	<head>
		<title>Editar cliente</title>
	</head>
	<body>
		
		<h1>Editar cliente</h1>
		<a href="{% url 'crud-r' %}">Regresar</a>

		<form action="" method="POST">
			{% csrf_token %}

			{{form.as_p}}

			<input type="submit" name="submit" value="Actualizar">
		</form>
	</body>
</html>			

apps/clientes/templates/clientes/delete.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% get_media_prefix as MEDIA_URL %}
{% get_static_prefix as STATIC_URL %}


{% block main %}
	<div class="row">        
    <div class="col-lg-8 equel-grid">      
      <div class="grid ">
        <div class="split-header">
          <p class="grid-header">Eliminar cliente</p>
          <a href="{% url 'clientes-list' %}" class="btn btn-rounded social-icon-btn btn-facebook right"><i class="mdi mdi-arrow-left"></i></a>          
        </div>
        <div class="grid-body">
          {% if messages %}
            {% for message in messages %}              
              <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{message}}
              </div>
            {% endfor %}
          {% endif %}
          {% if form.errors %}
            {% for error in form.errors %}
              <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                 {{error}}
              </div>
            {% endfor %}
          {% endif %}
          <div class="item-wrapper">
            <form method="post">
                {% csrf_token %}
                <div>
                  <div class="alert alert-danger alert-dismissible">
                    Seguro deseas borar a
                    {{cliente.full_name}}?
                  </div>
                    <input type="hidden" name="post" value="yes" />
                    <button class="btn btn-warning " type="submit">Sí, estoy seguro</button>
                    <a onclick="window.history.back();" class="btn btn-success text-white">No, regresar</a>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
	</div>
{% endblock %}

apps/clientes/templates/clientes/edit.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% get_media_prefix as MEDIA_URL %}
{% get_static_prefix as STATIC_URL %}


{% block main %}
	<div class="row">        
    <div class="col-lg-8 equel-grid">      
      <div class="grid ">
        <div class="split-header">
          <p class="grid-header">Editar cliente</p>
          <a href="{% url 'clientes-list' %}" class="btn btn-rounded social-icon-btn btn-facebook right"><i class="mdi mdi-arrow-left"></i></a>          
        </div>
        <div class="grid-body">
          {% if messages %}
            {% for message in messages %}              
              <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{message}}
              </div>
            {% endfor %}
          {% endif %}
          
          <div class="item-wrapper">
            <form method="post" action="" >
                {% csrf_token %}
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="id_first_name">Nombre</label>
                    {{ form.first_name }}

                    {% if form.first_name.errors %}
                      {% for error in form.first_name.errors %}
                        <li class="alert-danger">{{error}}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    <label for="id_last_name">Apellido</label>
                    {{ form.last_name }}
                    {% if form.last_name.errors %}
                      {% for error in form.last_name.errors %}
                        <li class="alert-danger">{{error}}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                    {% if form.email.errors %}
                      {% for error in form.email.errors %}
                        <li class="alert-danger">{{error}}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="row">
                    <div class="col-lg-9">
                      <div class="form-group">
                        <label for="id_phone">Teléfono</label>
                        {{ form.phone }}
                        {% if form.phone.errors %}
                          {% for error in form.phone.errors %}
                            <li class="alert-danger">{{error}}</li>
                          {% endfor %}
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-lg-2" style="top: 10px;">
                      <br>
                      <div class="checkbox">
                        <label for="id_last_name">
                          {{ form.status}}
                          Estado
                          <i class="input-frame"></i>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label for="id_address">Dirección</label>
                {{ form.address }}
                
                {% if form.address.errors %}
                  {% for error in form.address.errors %}
                    <li class="alert-danger">{{error}}</li>
                  {% endfor %}
                {% endif %}
              </div>
              <button type="submit" class="btn btn-sm btn-primary">Actualizar</button>
              <button type="submit" name="save-and-add" class="btn btn-sm btn-success">Actualizar y crear uno nuevo</button>              
            </form>
          </div>
        </div>
      </div>
    </div>
	</div>
{% endblock %}

apps/clientes/templates/clientes/index.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% get_media_prefix as MEDIA_URL %}
{% get_static_prefix as STATIC_URL %}
{% block extra_style %}
  	<style type="text/css">
  		.t-header-search-box2  {
  			display: flex;
		    width: 30%;
		    height: 40px !important;
		    background: #f3f5f6;
		    border-radius: 50px;
		    padding: 5px;
		    transition: 0.3s ease-in-out;
		    transition-property: "width";
		    overflow: hidden;
  		}
  		.t-header-search-box2 .form-control {
  			height: inherit;
  			border: none;
		    background: transparent;
		    font-size: 1rem;
		    font-weight: 500;
		    padding-left: 0;
		    padding: 5px 20px;
  		}
  		.t-header-search-box2 .input-group button {
  		    height: 100%;
  		    border-radius: 50px;
  		    padding: 0 7px;
  		    box-shadow: 0px 0px 5px -1px #696ffb;
  		    transition-duration: 0.3s;
  		}
  		.t-header-search-box2 .input-group a {
  		    height: 100%;
  		    border-radius: 50px;
  		    padding: 0 7px;
  		    box-shadow: 0px 0px 5px -1px #696ffb;
  		    transition-duration: 0.3s;
  		}
  	</style>
{% endblock %}

{% block main %}
	<div class="row">	 
	  	<div class="col equel-grid">
		    <div class="grid">
		      <div class="grid-body py-3 split-header">
		        <p class="card-title ml-n1">Clientes</p>
		        <form action="#" class="t-header-search-box2">
		          <div class="input-group">
		          	{% if name %}
		          		<input type="text"  value="{{name}}" autofocus onfocus="this.select()"  name="name" class="form-control" id="inlineFormInputGroup" placeholder="Nombre cliente" autocomplete="off">
		          	{% else %}
		          		<input type="text" autofocus name="name" class="form-control" id="inlineFormInputGroup" placeholder="Nombre o apelllido de cliente" autocomplete="off">
		          	{% endif %}
		            <button style="height: 32px;" title="Consultar" class="btn btn-primary" type="submit"><i class="mdi mdi-send"></i></button>
		        	<a title="Limpiar" style="height: 32px;" class="btn btn-danger" href="{% url 'clientes-list'%}"><i class="mdi mdi-window-close"></i></a>
		          </div>
		        </form>
		        {% if clientes.count > 0 %}
			        Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
				{% else %}
					<span class="alert alert-danger">
						Sin resultado
					</span>
				{% endif %}

		        <a title="Crear cliente" href="{% url 'clientes-new' %}" class="btn btn-rounded social-icon-btn btn-facebook right"><i class="mdi mdi-plus"></i></a>          
		      </div>
		      
		      {% if messages %}
		        {% for message in messages %}              
		          <div class="alert alert-success alert-dismissible">
		            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		             {{message}}
		          </div>
		        {% endfor %}
		      {% endif %}
		      <div class="table-responsive">
		        <table class="table table-hover table-sm">
		          <thead>
		            <tr class="solid-header">
		              <th colspan="2" class="pl-4">Nombre</th>
		              <th>Teléfono</th>
		              <th>Correo electrónico</th>
		              <th>Activo?</th>
		              <th>Opciones</th>
		            </tr>
		          </thead>
		          <tbody>
		          	{% for item in clientes %}
		            <tr>
		              <td class="pr-0 pl-4">
		                <img class="profile-img img-sm" src="{% static 'home/images/profile/male/image_4.png' %}" alt="profile image">
		              </td>
		              <td class="pl-md-0">
		                <small class="text-black font-weight-medium d-block">{{item.first_name}} {{item.last_name}}</small>
		                <span class="text-gray">
		                  <span class="status-indicator rounded-indicator small bg-primary"></span>{{item.address}} </span>
		              </td>
		              <td>
		                <small>{{item.phone}}</small>
		              </td>
		              <td> {{item.email}} </td>
		              <td>  
		              	{% if item.status %}
		              		<div class="badge badge-success">Sí</div>
		              	{% else %}
		              	 	<div class="badge badge-danger">No</div>
		              	{% endif %}
		          		</td>
		              <td>
		              	<div class="btn-group">
		              	  <button type="button" class="btn btn-trasnparent action-btn btn-xs component-flat pr-0" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		              	    <i class="mdi mdi-dots-vertical"></i>
		              	  </button>
		              	  <div class="dropdown-menu dropdown-menu-right">
		              	    <a class="dropdown-item" href="{% url 'clientes-delete' item.id %}">Eliminar</a>
		              	    <a class="dropdown-item" href="{% url  'clientes-edit' item.id %}">Editar</a>
		              	  </div>
		              	</div>
		              </td>
		            </tr>
		            {% endfor %}
		          </tbody>
		        </table>
		        <nav aria-label="Page navigation example">
		          <ul class="pagination justify-content-center">
	            	{% if page_obj.has_previous %}
	            		<li class="page-item">
	              			<a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Anterior</a>
	              		</li>
	              	{% else %}
	              		<li class="page-item disabled">
	              			<a class="page-link" href="#" tabindex="-1">Anterior</a>
	              		</li>
	              	{% endif %}		         
	              	{% for page in page_obj.paginator.page_range %}   
	              		{% if page == page_obj.number %}   
	              			<li class="page-item active" >
	              				<a class="page-link" href="#">{{page}}</a>
	              			</li>
	              		{% else %}
	              			<li class="page-item" >
	              				<a class="page-link" href="?page={{page}}">{{page}}</a>
	              			</li>
	              		{% endif %}
		            {% endfor %}
		            {% if page_obj.has_next %}
		            	<li class="page-item">
		              		<a class="page-link" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
		            	</li>
		            {% else %}
	            		<li class="page-item disabled">
	            	  		<a class="page-link" href="#">Siguiente</a>
	            		</li>
		            {% endif %}
		          </ul>
		        </nav>
		      </div>
		    </div>
	  	</div>
	</div>
{% endblock %}

apps/clientes/templates/clientes/new.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load static %}
{% get_media_prefix as MEDIA_URL %}
{% get_static_prefix as STATIC_URL %}


{% block main %}
	<div class="row">        
    <div class="col-lg-8 equel-grid">      
      <div class="grid ">
        <div class="split-header">
          <p class="grid-header">Crear cliente</p>
          <a title="Regresar" href="{% url 'clientes-list' %}" class="btn btn-rounded social-icon-btn btn-facebook right"><i class="mdi mdi-arrow-left"></i></a>          
        </div>
        <div class="grid-body">
          {% if messages %}
            {% for message in messages %}              
              <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                 {{message}}
              </div>
            {% endfor %}
          {% endif %}
          
          <div class="item-wrapper">
            <form method="post" action="" >
                {% csrf_token %}
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="id_first_name">Nombre</label>
                    {{ form.first_name }}
                    {% if form.first_name.errors %}
                      {% for error in form.first_name.errors %}
                        <li class="alert-danger">{{error}}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    <label for="id_last_name">Apellido</label>
                    {{ form.last_name }}
                    {% if form.last_name.errors %}
                      {% for error in form.last_name.errors %}
                        <li class="alert-danger">{{error}}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                    {% if form.email.errors %}
                      {% for error in form.email.errors %}
                        <li class="alert-danger">{{error}}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                  <div class="row">
                    <div class="col-lg-9">
                      <div class="form-group">
                        <label for="id_phone">Teléfono</label>
                        {{ form.phone }}
                        {% if form.phone.errors %}
                          {% for error in form.phone.errors %}
                            <li class="alert-danger">{{error}}</li>
                          {% endfor %}
                        {% endif %}
                      </div>
                    </div>
                    <div class="col-lg-2" style="top: 10px;">
                      <br>
                      <div class="checkbox">
                        <label for="id_last_name">
                          {{ form.status}}
                          Estado
                          <i class="input-frame"></i>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label for="id_address">Dirección</label>
                {{ form.address }}
                {% if form.address.errors %}
                  {% for error in form.address.errors %}
                    <li class="alert-danger">{{error}}</li>
                  {% endfor %}
                {% endif %}
              </div>
              <button type="submit" class="btn btn-sm btn-primary">Guardar</button>
              <button type="submit" name="save-and-add" class="btn btn-sm btn-success">Guardar y crear uno nuevo</
            </form>
          </div>
        </div>
      </div>
    </div>
	</div>
{% endblock %}